import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin2@example.com',
      password: bcrypt.hashSync('@123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user2@example.com',
      password: bcrypt.hashSync('@123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'banner1',
      slug: 'banner-1',
      category: 'banner',
      image: '/images/banner1.jpg',
      // price: 1,
      brand: 'fashion',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'high quality product',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'banner2',
      slug: 'banner-2',
      category: 'banner',
      image: '/images/banner2.jpg',
      // price: 1,
      brand: 'fashion',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'high quality product',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'banner3',
      slug: 'banner-3',
      category: 'banner',
      image: '/images/banner3.jpg',
      // price: 1,
      brand: 'fashion',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'high quality product',
      isFeatured: true,
      banner: '/images/banner3.jpg',
    },
    {
      name: 'vest',
      slug: 'men-vest',
      category: 'men',
      image: '/images/topt.jpg',
      price: 1,
      brand: 'hucai',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'gym tights',
      slug: 'gym-tygy',
      category: 'ladies',
      image: '/images/gymsuit.jpg',
      price: 1,
      brand: 'logo',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'sweatsuit',
      slug: 'sweat-suit',
      category: 'men',
      image: '/images/sweats.jpg',
      price: 1,
      brand: 'logo',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'boxing gloves',
      slug: 'box-ing',
      category: 'unisex',
      image: '/images/box.jpg',
      price: 1,
      brand: 'PowerLine',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'yoga suit',
      slug: 'yoga-suit',
      category: 'Suspension',
      image: '/images/yogasuit.jpg',
      price: 1,
      brand: 'Magnum',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'latex bands',
      slug: 'latex',
      category: 'ladies',
      image: '/images/latex.jpg',
      price: 1,
      brand: 'juakali',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'gym wear',
      slug: 'gym-wear',
      category: 'men',
      image: '/images/gymwear.jpg',
      price: 1,
      brand: 'juakali',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'banner',
      slug: 'banner-gym',
      category: 'ladies',
      image: '/images/banner.jpg',
      // price: 1,
      brand: 'Champion',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
      isFeatured: true,
      banner: '/images/banner.jpg',
    },
    {
      name: 'yoga mat',
      slug: 'yoga-mat',
      category: 'unisex',
      image: '/images/yogamat.jpg',
      price: 1,
      brand: 'Bosch',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
  ],
};

export default data;
